<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Trip extends \App\Entity\Trip implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activities' => [parent::class, 'activities', null],
        "\0".parent::class."\0".'admin' => [parent::class, 'admin', null],
        "\0".parent::class."\0".'backgroundPicture' => [parent::class, 'backgroundPicture', null],
        "\0".parent::class."\0".'cities' => [parent::class, 'cities', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'endDate' => [parent::class, 'endDate', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'startDate' => [parent::class, 'startDate', null],
        "\0".parent::class."\0".'travelers' => [parent::class, 'travelers', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'activities' => [parent::class, 'activities', null],
        'admin' => [parent::class, 'admin', null],
        'backgroundPicture' => [parent::class, 'backgroundPicture', null],
        'cities' => [parent::class, 'cities', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'description' => [parent::class, 'description', null],
        'endDate' => [parent::class, 'endDate', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'startDate' => [parent::class, 'startDate', null],
        'travelers' => [parent::class, 'travelers', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
