<?php

namespace ContainerBZladL5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__EPpOA0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..ePpOA0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..ePpOA0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'itemRepository' => ['privates', 'App\\Repository\\ItemRepository', 'getItemRepositoryService', true],
            'trip' => ['privates', '.errored..service_locator..ePpOA0.App\\Entity\\Trip', NULL, 'Cannot autowire service ".service_locator..ePpOA0": it needs an instance of "App\\Entity\\Trip" but this type has been excluded in "config/services.yaml".'],
        ], [
            'itemRepository' => 'App\\Repository\\ItemRepository',
            'trip' => 'App\\Entity\\Trip',
        ]);
    }
}
