<?php

namespace ContainerBZladL5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ASg33aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a_Sg33a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a_Sg33a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'vote' => ['privates', '.errored..service_locator.a_Sg33a.App\\Entity\\Vote', NULL, 'Cannot autowire service ".service_locator.a_Sg33a": it needs an instance of "App\\Entity\\Vote" but this type has been excluded in "config/services.yaml".'],
        ], [
            'vote' => 'App\\Entity\\Vote',
        ]);
    }
}
