<?php

namespace ContainerBZladL5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4H83jreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4H83jre' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4H83jre'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'trip' => ['privates', '.errored..service_locator.4H83jre.App\\Entity\\Trip', NULL, 'Cannot autowire service ".service_locator.4H83jre": it needs an instance of "App\\Entity\\Trip" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'trip' => 'App\\Entity\\Trip',
        ]);
    }
}
