<?php

namespace ContainerBZladL5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Avfua8HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.avfua8H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.avfua8H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'friend' => ['privates', '.errored..service_locator.avfua8H.App\\Entity\\Friend', NULL, 'Cannot autowire service ".service_locator.avfua8H": it needs an instance of "App\\Entity\\Friend" but this type has been excluded in "config/services.yaml".'],
        ], [
            'friend' => 'App\\Entity\\Friend',
        ]);
    }
}
