<?php

namespace ContainerBZladL5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityScoreListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\ActivityScoreListener' shared autowired service.
     *
     * @return \App\EventListener\ActivityScoreListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/ActivityScoreListener.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventListener\\ActivityScoreListener'])) {
            return $container->privates['App\\EventListener\\ActivityScoreListener'];
        }

        return $container->privates['App\\EventListener\\ActivityScoreListener'] = new \App\EventListener\ActivityScoreListener(($container->privates['App\\Repository\\VoteRepository'] ?? $container->load('getVoteRepositoryService')), $a);
    }
}
