<?php

namespace ContainerBZladL5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Back\TripController' shared autowired service.
     *
     * @return \App\Controller\Back\TripController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Back/TripController.php';

        $container->services['App\\Controller\\Back\\TripController'] = $instance = new \App\Controller\Back\TripController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Back\\TripController', $container));

        return $instance;
    }
}
