<?php

namespace ContainerBZladL5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVote2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pzYdd46.App\Entity\Vote' shared service.
     *
     * @return \App\Entity\Vote
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.pzYdd46": it needs an instance of "App\\Entity\\Vote" but this type has been excluded in "config/services.yaml".');
    }
}
