<?php

namespace ContainerPdyx4kS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6RWZUz3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6RWZUz3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6RWZUz3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'request' => ['privates', '.errored..service_locator.6RWZUz3.Symfony\\Component\\BrowserKit\\Request', NULL, 'Cannot autowire service ".service_locator.6RWZUz3": it references class "Symfony\\Component\\BrowserKit\\Request" but no such service exists.'],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'em' => '?',
            'request' => 'Symfony\\Component\\BrowserKit\\Request',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
