<?php

namespace ContainerPdyx4kS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KQbHgo6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KQbHgo6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KQbHgo6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'item' => ['privates', '.errored..service_locator.KQbHgo6.App\\Entity\\Item', NULL, 'Cannot autowire service ".service_locator.KQbHgo6": it needs an instance of "App\\Entity\\Item" but this type has been excluded in "config/services.yaml".'],
            'userVerification' => ['privates', 'App\\Service\\UserVerification', 'getUserVerificationService', true],
        ], [
            'entityManager' => '?',
            'item' => 'App\\Entity\\Item',
            'userVerification' => 'App\\Service\\UserVerification',
        ]);
    }
}
