<?php

namespace ContainerPdyx4kS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UZuct7WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uZuct7W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uZuct7W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'country' => ['privates', '.errored..service_locator.uZuct7W.App\\Entity\\Country', NULL, 'Cannot autowire service ".service_locator.uZuct7W": it needs an instance of "App\\Entity\\Country" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'imageHandler' => ['privates', 'App\\Service\\ImageHandler', 'getImageHandlerService', true],
        ], [
            'country' => 'App\\Entity\\Country',
            'entityManager' => '?',
            'imageHandler' => 'App\\Service\\ImageHandler',
        ]);
    }
}
