<?php

namespace ContainerPdyx4kS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2LfNPfQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2LfNPfQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2LfNPfQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'friend' => ['privates', '.errored..service_locator.2LfNPfQ.App\\Entity\\Friend', NULL, 'Cannot autowire service ".service_locator.2LfNPfQ": it needs an instance of "App\\Entity\\Friend" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'friend' => 'App\\Entity\\Friend',
        ]);
    }
}
