<?php

namespace ContainerPdyx4kS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriend2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Irvp3Wx.App\Entity\Friend' shared service.
     *
     * @return \App\Entity\Friend
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Irvp3Wx": it needs an instance of "App\\Entity\\Friend" but this type has been excluded in "config/services.yaml".');
    }
}
