<?php

namespace ContainerPdyx4kS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserVerificationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\UserVerification' shared autowired service.
     *
     * @return \App\Service\UserVerification
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/UserVerification.php';

        $a = ($container->privates['App\\Service\\UserFinder'] ?? $container->load('getUserFinderService'));

        if (isset($container->privates['App\\Service\\UserVerification'])) {
            return $container->privates['App\\Service\\UserVerification'];
        }

        return $container->privates['App\\Service\\UserVerification'] = new \App\Service\UserVerification($a);
    }
}
